enum LightboxActionType {
  LIGHT_BOX_OPEN = "LIGHT_BOX_OPEN",
  LIGHT_BOX_CLOSE = "LIGHT_BOX_CLOSE",
  LIGHT_BOX_OPEN_BY_PHOTO_INDEX = "LIGHT_BOX_OPEN_BY_PHOTO_INDEX",
  LIGHT_BOX_MOVE_PHOTO_BY_INDEX = "LIGHT_BOX_MOVE_PHOTO_BY_INDEX",
}

export { LightboxActionType };
