enum SelectActionType {
  SELECT_SET_IMAGE = "SELECT_SET_IMAGE",
  DESELECT_IMAGE = "DESELECT_IMAGE",
  SELECT_ALL_IMAGES = "SELECT_ALL_IMAGES",
  DESELECT_ALL_IMAGES = "DESELECT_ALL_IMAGES",
}

export { SelectActionType };
